version: "3.9"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"

  client:
    container_name: frontend
    build:
      context: ./web
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
